[phases.setup]
nixPkgs = ["nodejs_22", "nodePackages.pnpm"]

[phases.install]
cmds = ["pnpm install --ignore-scripts"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "npx serve dist/public -p 8080"